-- Create posts table
CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert 50 dummy posts
INSERT INTO posts (title) VALUES
('The Future of Web Development'),
('Understanding TypeScript Basics'),
('Building RESTful APIs'),
('Introduction to PostgreSQL'),
('Modern JavaScript Patterns'),
('Database Design Best Practices'),
('Getting Started with Bun'),
('CSS Grid Layout Guide'),
('React Hooks Explained'),
('Node.js Performance Tips'),
('Docker Containerization'),
('Git Workflow Strategies'),
('API Security Essentials'),
('Microservices Architecture'),
('GraphQL vs REST'),
('Cloud Computing Basics'),
('DevOps Best Practices'),
('Testing Strategies'),
('Code Review Guidelines'),
('Agile Development Methods'),
('Frontend Frameworks Comparison'),
('Backend Architecture Patterns'),
('Database Optimization'),
('Web Security Fundamentals'),
('Mobile App Development'),
('Machine Learning Basics'),
('Data Structures and Algorithms'),
('System Design Principles'),
('Network Protocols Explained'),
('Software Engineering Practices'),
('UI/UX Design Principles'),
('Version Control Systems'),
('Continuous Integration'),
('Deployment Strategies'),
('Performance Optimization'),
('Error Handling Techniques'),
('Documentation Standards'),
('Code Quality Metrics'),
('Team Collaboration Tools'),
('Project Management Methods'),
('Technical Writing Skills'),
('Open Source Contributions'),
('Career Development Tips'),
('Learning Resources Guide'),
('Industry Trends Analysis'),
('Technology Stack Selection'),
('Scalability Considerations'),
('Maintenance Best Practices'),
('User Experience Design'),
('Accessibility Standards'),
('Modern Development Tools');
